sudo: required
dist: trusty
language: node_js
node_js:
- '8'
git:
  depth: 3
addons:
  ssh_known_hosts:
  - web-standards.ru
  - wsd.events
before_deploy:
- openssl aes-256-cbc -K $encrypted_d4de074d2938_key -iv $encrypted_d4de074d2938_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d
- .travis/set-up-ssh
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: master
